tools:
  php_code_sniffer:
    config:
      standard: WordPress
  sensiolabs_security_checker: true
checks:
  php:
    coding_standard:
      name: WordPress
filter:
  excluded_paths:
    - vendor/
    - storage/
    - node_modules/